import type { Metadata } from 'next';
import './globals.css';
import { Dashboard } from '../components/Dashboard';
import { TopNavigation } from '@/components/TopNavigation';
import { Logo } from '@/components/Logo';

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='flex flex-col bg-grayscale-background-subtle'>
        <TopNavigation />
        <main className='flex flex-col p-24 pt-32 '>
          <Dashboard>{children}</Dashboard>
        </main>
        <footer className='flex flex-col  fixed bottom-0 z-50  bg-grayscale-background-subtle w-full px-24 pb-10 pt-6'>
          <div className='flex flex-row items-center justify-center  w-[126px] h-[31px]'>
            <Logo />
          </div>
          <p className='text-left text-xs text-grayscale-textIcon-caption size-1 w-full'>
            © www.takes-care.com 2024
          </p>
        </footer>
      </body>
    </html>
  );
}
